### ISSUE TITLE
Issue with working in non-legacy PowerShell console Windows 10

### ISSUE THREAD

**Issue by denis-a-evdokimov** [tillig/ps-bash-completions#6] opened 2019-03-09 00:35 UTC
I'm using PowerShell v. 5.1 on Microsoft Windows 10 Pro for Workstations v. 10.0.17763 Build 17763

When PowerShell console in is started in non-legacy mode then script is not working.
Below result of completing "kubectl c": 

![image](https://user-images.githubusercontent.com/19668152/54063117-bc6ee080-420a-11e9-8fed-b4e72e94521a.png)

Debug have shown me correct command just before calling this block:
$result | ForEach-Object {
      [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
Direct call bash return correct list of completion strings.
If use WindowsPowerShell ISE or PowerShell console in legacy mode - all is fine.
Can be marked as Known Issue.

**Comment by tillig** [comment] 2019-03-09 01:23
It looks like ANSI color codes are getting stuck in there. Hmmm. I wonder if there's something that can be done about that. Let me see if I can reproduce it.

**Comment by tillig** [comment] 2019-03-11 14:59
I have never used legacy console mode and I also have never seen the ANSI codes come through like this.

![No legacy console, no ](https://user-images.githubusercontent.com/1156571/54133021-8aa87600-43d2-11e9-9fa9-fa8949708038.jpg)

I'm on the same PowerShell and OS as you, too.

Try something:

Go into the installed module and open `PSBashCompletions.psm1` in a text editor. [Scroll down to line 149 where you see this](https://github.com/tillig/ps-bash-completions/blob/8e20d54119f208f0448909587bbea59784ace4c5/PSBashCompletions/PSBashCompletions.psm1#L149):

```ps
$result = (&"$bash" "$bashBridgeScript" "$bashCompletionScript" "$encodedCommand")
```

Update it to this:

```ps
$result = (&"$bash" "--noprofile" "--norc" "$bashBridgeScript" "$bashCompletionScript" "$encodedCommand")
```

What I'm thinking is there may be something in your bash profile that is sticking ANSI color codes in there.

You may need to close and re-open all PowerShell prompts to see the change.

**Comment by denis-a-evdokimov** [comment] 2019-03-11 20:11
Have tried this out, still same result:
![image](https://user-images.githubusercontent.com/19668152/54154491-494faf00-4442-11e9-8a16-4f65f5495b06.png)

**Comment by tillig** [comment] 2019-03-11 20:15
Well... uh... since I can't reproduce it, I'm not sure that I can do much more to debug it. That was my one idea.

I'll leave the issue open in case you figure it out or someone else comes along and sees this as well. If we can figure out what's causing it, it may be something we can fix.

**Comment by denis-a-evdokimov** [comment] 2019-03-11 20:20
Also right now I've tried to put
```
Set-Clipboard -Value $result;
```

just before processing the results. Ctrl-V after that is fine:
![image](https://user-images.githubusercontent.com/19668152/54154946-54570f00-4443-11e9-9c48-54aaf20c6dc4.png)
Moreover - I press enter after those strange ANSI color codes and looks like command was fine, help text about 'containers' were shown.
I will try to look what else will work anyway,

**Comment by tillig** [comment] 2019-05-16 16:03
Closing this issue until more information can be provided. It's been a couple of months, I'm not sure leaving it open much longer is going to help. If others hit this, I'll need more information about how to reproduce the problem before I can take action.

**Closed as completed by tillig** 2019-05-16 16:03 UTC

**Comment by pepekpl** [comment] 2020-01-23 17:19
I have the same issue. Using Windows 10, PS version  5.1.17763.771
I have Current code page set to 850 (OEM - Multilingual Latin I) if that helps you with debugging.
